name = "Vanilla Modded"
author = "nicoladen05"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9536f77c2a8b449b151afcae484b858957448d9f125fddd547d0a18ee38bfbf3"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.20.4", "1.20.6"]
