name = "Vanilla Modded"
author = "nicoladen05"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bdc2091dc7d12b81502ad50c7f818b8781615b2d43f29145bfeeec58d4d46c2"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"

[options]
acceptable-game-versions = ["1.20.6"]
