name = "Vanilla Modded"
author = "nicoladen05"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07ea3e22a7f9866822b70c7fde819251104959b4f988e75a8eaa0afcea083de7"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"

[options]
acceptable-game-versions = ["1.20.4", "1.20.6"]
