name = "Vanilla Modded"
author = "nicoladen05"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6bac840f301999282e25eac5d84a35bd9daeb7846add16c50ce61951866173d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
